services:
  api:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app/app
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      # Which summarization model to use: "distilbart", "bart-large", or "flan-t5"
      # Make sure to also pre-download the chosen model in the Dockerfile.
      # - SUMMARIZATION_MODEL=distilbart
      - SUMMARIZATION_MODEL=bart-large
      # - SUMMARIZATION_MODEL=flan-t5
